### ISSUE TITLE
Write good tests

### ISSUE THREAD

**Issue by ananyo2012** [Abhi2424shek/img_checker#11]
Obviously writing good tests is essential, even if this is a small gem it needs to have tests right from the beginning! Follow docs on `Rspec` or Ruby's default `Test::Unit` to write tests and get them running in CI as well.

**Comment by ankitrgadiya** [comment]
@Abhi2424shek I added test images but I thing we should not just edit config.yml we should add tests.
http://guides.rubygems.org/make-your-own-gem/#writing-tests

**Comment by ananyo2012** [comment]
@Abhi2424shek Used the wrong issue no I guess. You should reopen this.

**Comment by Abhi2424shek** [comment]
Sorry

**Comment by Abhi2424shek** [comment]
Done
