### ISSUE TITLE
Add automatic deployment

### ISSUE THREAD

**Issue by ankitrgadiya** [Abhi2424shek/img_checker#21]
We need to automatically deploy it.
Currently we are using Rultor, but its not working.
Also we're having a api file, which is publically available which is not good either.

I propose to use Travis again, as it supports variable and is in my view much easier to use.

**Comment by Abhi2424shek** [comment]
Rultor is much more powerful we need to configure it properly, let's just have a try, @rultor please deploy, tag is `1.1`

**Comment by Abhi2424shek** [comment]
@rultor please release, tag is `1.1`

**Comment by Abhi2424shek** [comment]
@rultor please release, tag is `1.1`

**Comment by Abhi2424shek** [comment]
@rultor please release, tag is `1.1`

**Comment by Abhi2424shek** [comment]
It's done @ankitrgadiya just fixed rultor now we can use it
