### ISSUE TITLE
Give your feature requests here

### ISSUE THREAD

**Issue by ankitrgadiya** [Abhi2424shek/img_checker#24]
Add your feature requests here first, if it get's accepted pls open a relevant issue for the same.
_Note: Bugs and other questions should not go in here, a new issue must be opened for each bug encountered, only feature requests should be here._

**Comment by Abhi2424shek** [comment]
@ankitrgadiya, I've had a suggestion from @rhemon for a feature, we could use this issue as a channel for new feature requests and make issues for them if we all feel it's a good idea!

**Comment by ankitrgadiya** [comment]
@Abhi2424shek sure, its a good way.

**Comment by rhemon** [comment]
the feature i requested was that the gem should accept any file, like `img_checker just-a-file.yml` and use that rather than just looking for `img_checker.yml`. this will help avoild conflicts.

**Comment by ankitrgadiya** [comment]
@Abhi2424shek we can make a flag ```-c``` as in Config to accept config files. But since there's a separate issue to remove config file so what's your opinion??

**Comment by Abhi2424shek** [comment]
Open one, add an ignore config file and parser too.

**Comment by Abhi2424shek** [comment]
We'd follow the official way opening an issue for a request or this would seem bad so closing this!
