### ISSUE TITLE
Create a rultor config file and replace Travis deployment with rultor

### ISSUE THREAD

**Issue by Abhi2424shek** [Abhi2424shek/img_checker#3]
Rultor is great in deploying and we just need to comment on pr merges and things, it's easy. So we need to configure it.

**Comment by ankitrgadiya** [comment]
@Abhi2424shek Great. I'll read the docs and configure it.

**Comment by Abhi2424shek** [comment]
Yep then we need to deploy also so pls do the needed besides from now we will merge with rultor only.

**Comment by ankitrgadiya** [comment]
Sure!

**Comment by Abhi2424shek** [comment]
Any progress @ankitrgadiya

**Comment by Abhi2424shek** [comment]
Done then. @rultor hello

**Comment by ankitrgadiya** [comment]
@Abhi2424shek It will probably not work right now, we need to add rultor as collaborator.

**Comment by Abhi2424shek** [comment]
It was added @ankitrgadiya
