### ISSUE TITLE
Introduce cbot

### ISSUE THREAD

**Issue by Abhi2424shek** [Abhi2424shek/img_checker#33]
A new bot account should be created and can be used to push back changes as well as for code checking using various CIs

**Comment by ankitrgadiya** [comment]
This would be awesome to have one like Rultor bot and Checkbot
+1

**Comment by Abhi2424shek** [comment]
@ankitrgadiya maybe in the future we would open up a repository for it and deploy the repository would be hosted on something like heroku and would be made available to all the github users. :)

**Comment by ankitrgadiya** [comment]
@Abhi2424shek Sure that would be awesome. That also means that there is no need to use other CI(s) to test images, users just need to enable our bot and that will be it.

**Comment by Abhi2424shek** [comment]
Yes a bot as a front-end for our ruby gem, that will rock, well let me see to this, which language should we go with?

**Comment by ankitrgadiya** [comment]
@Abhi2424shek I'm trying out python these days (taking MIT6.00.1x) so we can go with python. Although I'm not very experienced in any language so I'm probably not the right person to answer this. What are your suggestions?

**Comment by Abhi2424shek** [comment]
Well i know nothing python, as far as you know I only know C, HTML, CSS, Java, Javascript and Ruby. So basically, as far as I am concerned in my view a nodejs app would do, I would learn it and it is ideally needy for every developer (web). I hate python. Well we could either go with Java (Simple) or nodejs in my view let me have yours please.

**Comment by ankitrgadiya** [comment]
I'm not familiar with either but Nodejs is on my list to learn so we can try with it.

**Comment by Abhi2424shek** [comment]
Yep I would create a repository.

**Comment by Abhi2424shek** [comment]
Can we have the name as img_bot?

**Comment by Abhi2424shek** [comment]
We would continue on github.com/abhi2424shek/img_bot/issues/1
