### ISSUE TITLE
Add other CI tests

### ISSUE THREAD

**Issue by Abhi2424shek** [Abhi2424shek/img_checker#4]
We need to test this script on multiple CI tests for better perofmance so we need to implement the same. Here is a list i got:

- [ ] circle ci to run in 2.0
- [x] snap ci to run in ruby 2.1

We will use multiple ruby versions for each one of them. We will need to run the script that's all. After that add the status to the readme file as well.

**Comment by ankitrgadiya** [comment]
Which tests we need to do??

**Comment by Abhi2424shek** [comment]
Just the current ones, we will close when finished by circle ci

**Comment by Abhi2424shek** [comment]
We would run Travis parallel and that would save us..

**Comment by ankitrgadiya** [comment]
Yeah sure! 👍
