### ISSUE TITLE
Name Class as per the gem name

### ISSUE THREAD

**Issue by ananyo2012** [Abhi2424shek/img_checker#5]
The convention is naming the topmost module or class name similar to the gem name. Here it should be `ImgChecker`

**Comment by Abhi2424shek** [comment]
The class would not be used and there is a convention to use snace_names so we will rename it to something like `img_checker.rb` but it won't be necessary although as the class needs not to be called!

**Comment by ankitrgadiya** [comment]
@Abhi2424shek we have to use ImgChecker, as we cannot start the class name with lowercase. Also Rubocap's throughing errors for using CamelCase.
```
lib/img_checker.rbm:19:7: C: Use CamelCase for classes and modules.

class Img_checker
```
