### ISSUE TITLE
Add rubocop lint configs in .rubocop.yml

### ISSUE THREAD

**Issue by ananyo2012** [Abhi2424shek/img_checker#6]
You can follow the [bundler rubocop config](https://github.com/bundler/bundler/blob/master/.rubocop.yml) for this

**Comment by Abhi2424shek** [comment]
It's just small piece of code we would just have robocop to check only a specific file and will follow the default conventions we could apply this when the code base becomes large.

**Comment by ananyo2012** [comment]
Yeah can be labelled as low priority as of now

**Comment by Abhi2424shek** [comment]
I don't know whether we would need it so we will open this when the code looms large ;)
