### ISSUE TITLE
Make separate module for Class

### ISSUE THREAD

**Issue by ananyo2012** [Abhi2424shek/img_checker#9]
It is a cleaner approach to keep the Class separate in a separate module and keep the driver code separate. Keep [these lines](https://github.com/Abhi2424shek/img_checker/blob/master/lib/img_checker.rb#L73-L81) in `image_checker.rb` and make a separate `lib/img_checker/img_size_linter.rb` file and put the class there. You can follow the [rubygems guide](http://guides.rubygems.org/make-your-own-gem/#requiring-more-files) on how to add more files.

**Comment by Abhi2424shek** [comment]
@ananyo2012 as I said earlier we are sall codes of just 60 lines and we don't want to make it seprate.

**Comment by ananyo2012** [comment]
Even it is a small code you SHOULD emphasize on writing better code as a gem author. Keeping the driver code and classes in the same file is not how gem conventions go. It would be then equivalent to writing a ruby script.

**Comment by Abhi2424shek** [comment]
Ok then we will work on it...
